# antipattern count variables:

bitly_isBreakingSelfDescriptiveness=11
bitly_isForgettingHypermedia=0
bitly_isIgnoringCaching=0
bitly_isIgnoringMIMEType=0
bitly_isIgnoringStatusCode=0
bitly_isMisusingCookies=0
bitly_AmorphousURI=0
bitly_CRUDyURI=0
bitly_ContextlessResource=9

twitter_isBreakingSelfDescriptiveness=61
twitter_isForgettingHypermedia=0
twitter_isIgnoringCaching=0
twitter_isIgnoringMIMEType=0
twitter_isIgnoringStatusCode=0
twitter_isMisusingCookies=61
twitter_AmorphousURI=0
twitter_CRUDyURI=26
twitter_ContextlessResource=5

disqus_isBreakingSelfDescriptiveness=37
disqus_isForgettingHypermedia=0
disqus_isIgnoringCaching=0
disqus_isIgnoringMIMEType=0
disqus_isIgnoringStatusCode=0
disqus_isMisusingCookies=0
disqus_AmorphousURI=37
disqus_CRUDyURI=1
disqus_ContextlessResource=5

#antipatterns

mydata <- matrix(c(bitly_isBreakingSelfDescriptiveness, bitly_isForgettingHypermedia, bitly_isIgnoringCaching, bitly_isIgnoringMIMEType, bitly_isIgnoringStatusCode, bitly_isMisusingCookies, bitly_AmorphousURI, bitly_CRUDyURI, bitly_ContextlessResource, 
twitter_isBreakingSelfDescriptiveness, twitter_isForgettingHypermedia, twitter_isIgnoringCaching, twitter_isIgnoringMIMEType, twitter_isIgnoringStatusCode, twitter_isMisusingCookies, twitter_AmorphousURI, twitter_CRUDyURI, twitter_ContextlessResource, 
disqus_isBreakingSelfDescriptiveness, disqus_isForgettingHypermedia, disqus_isIgnoringCaching, disqus_isIgnoringMIMEType, disqus_isIgnoringStatusCode, disqus_isMisusingCookies, disqus_AmorphousURI, disqus_CRUDyURI, disqus_ContextlessResource), nrow=3,
ncol=9,byrow = TRUE)

chisq.test(mydata)
