# antipattern count variables:

bitly_isBreakingSelfDescriptiveness=16
bitly_isForgettingHypermedia=0
bitly_isIgnoringCaching=0
bitly_isIgnoringMIMEType=0
bitly_isIgnoringStatusCode=0
bitly_isMisusingCookies=0
bitly_AmorphousURI=0
bitly_ContextlessResource=10
bitly_CRUDyURI=0
bitly_NonHierarchicalNodes=0
bitly_PluralisedNodes=3

imgur_isBreakingSelfDescriptiveness=53
imgur_isForgettingHypermedia=0
imgur_isIgnoringCaching=0
imgur_isIgnoringMIMEType=1
imgur_isIgnoringStatusCode=0
imgur_isMisusingCookies=3
imgur_AmorphousURI=0
imgur_ContextlessResource=1
imgur_CRUDyURI=0
imgur_NonHierarchicalNodes=0
imgur_PluralisedNodes=5

vimeo_isBreakingSelfDescriptiveness=58
vimeo_isForgettingHypermedia=0
vimeo_isIgnoringCaching=0
vimeo_isIgnoringMIMEType=58
vimeo_isIgnoringStatusCode=0
vimeo_isMisusingCookies=0
vimeo_AmorphousURI=0
vimeo_ContextlessResource=2
vimeo_CRUDyURI=0
vimeo_NonHierarchicalNodes=0
vimeo_PluralisedNodes=0

disqus_isBreakingSelfDescriptiveness=48
disqus_isForgettingHypermedia=0
disqus_isIgnoringCaching=0
disqus_isIgnoringMIMEType=0
disqus_isIgnoringStatusCode=4
disqus_isMisusingCookies=4
disqus_AmorphousURI=36
disqus_ContextlessResource=6
disqus_CRUDyURI=1
disqus_NonHierarchicalNodes=0
disqus_PluralisedNodes=7

facebook_isBreakingSelfDescriptiveness=19
facebook_isForgettingHypermedia=0
facebook_isIgnoringCaching=0
facebook_isIgnoringMIMEType=0
facebook_isIgnoringStatusCode=0
facebook_isMisusingCookies=0
facebook_AmorphousURI=0
facebook_ContextlessResource=2
facebook_CRUDyURI=0
facebook_NonHierarchicalNodes=0
facebook_PluralisedNodes=0

github_isBreakingSelfDescriptiveness=30
github_isForgettingHypermedia=0
github_isIgnoringCaching=0
github_isIgnoringMIMEType=30
github_isIgnoringStatusCode=0
github_isMisusingCookies=0
github_AmorphousURI=0
github_ContextlessResource=10
github_CRUDyURI=0
github_NonHierarchicalNodes=0
github_PluralisedNodes=6

stackExchange_isBreakingSelfDescriptiveness=34
stackExchange_isForgettingHypermedia=0
stackExchange_isIgnoringCaching=0
stackExchange_isIgnoringMIMEType=0
stackExchange_isIgnoringStatusCode=0
stackExchange_isMisusingCookies=34
stackExchange_AmorphousURI=0
stackExchange_ContextlessResource=4
stackExchange_CRUDyURI=0
stackExchange_NonHierarchicalNodes=0
stackExchange_PluralisedNodes=0

twitter_isBreakingSelfDescriptiveness=59
twitter_isForgettingHypermedia=0
twitter_isIgnoringCaching=0
twitter_isIgnoringMIMEType=0
twitter_isIgnoringStatusCode=0
twitter_isMisusingCookies=59
twitter_AmorphousURI=0
twitter_ContextlessResource=9
twitter_CRUDyURI=24
twitter_NonHierarchicalNodes=0
twitter_PluralisedNodes=18

#antipatterns

mydata <- matrix(c(bitly_isBreakingSelfDescriptiveness, bitly_isForgettingHypermedia, bitly_isIgnoringCaching, bitly_isIgnoringMIMEType, bitly_isIgnoringStatusCode, bitly_isMisusingCookies, bitly_AmorphousURI, bitly_ContextlessResource, bitly_CRUDyURI, bitly_NonHierarchicalNodes, bitly_PluralisedNodes, 
imgur_isBreakingSelfDescriptiveness, imgur_isForgettingHypermedia, imgur_isIgnoringCaching, imgur_isIgnoringMIMEType, imgur_isIgnoringStatusCode, imgur_isMisusingCookies, imgur_AmorphousURI, imgur_ContextlessResource, imgur_CRUDyURI, imgur_NonHierarchicalNodes, imgur_PluralisedNodes, 
vimeo_isBreakingSelfDescriptiveness, vimeo_isForgettingHypermedia, vimeo_isIgnoringCaching, vimeo_isIgnoringMIMEType, vimeo_isIgnoringStatusCode, vimeo_isMisusingCookies, vimeo_AmorphousURI, vimeo_ContextlessResource, vimeo_CRUDyURI, vimeo_NonHierarchicalNodes, vimeo_PluralisedNodes, 
disqus_isBreakingSelfDescriptiveness, disqus_isForgettingHypermedia, disqus_isIgnoringCaching, disqus_isIgnoringMIMEType, disqus_isIgnoringStatusCode, disqus_isMisusingCookies, disqus_AmorphousURI, disqus_ContextlessResource, disqus_CRUDyURI, disqus_NonHierarchicalNodes, disqus_PluralisedNodes, 
facebook_isBreakingSelfDescriptiveness, facebook_isForgettingHypermedia, facebook_isIgnoringCaching, facebook_isIgnoringMIMEType, facebook_isIgnoringStatusCode, facebook_isMisusingCookies, facebook_AmorphousURI, facebook_ContextlessResource, facebook_CRUDyURI, facebook_NonHierarchicalNodes, facebook_PluralisedNodes, 
github_isBreakingSelfDescriptiveness, github_isForgettingHypermedia, github_isIgnoringCaching, github_isIgnoringMIMEType, github_isIgnoringStatusCode, github_isMisusingCookies, github_AmorphousURI, github_ContextlessResource, github_CRUDyURI, github_NonHierarchicalNodes, github_PluralisedNodes, 
stackExchange_isBreakingSelfDescriptiveness, stackExchange_isForgettingHypermedia, stackExchange_isIgnoringCaching, stackExchange_isIgnoringMIMEType, stackExchange_isIgnoringStatusCode, stackExchange_isMisusingCookies, stackExchange_AmorphousURI, stackExchange_ContextlessResource, stackExchange_CRUDyURI, stackExchange_NonHierarchicalNodes, stackExchange_PluralisedNodes, 
twitter_isBreakingSelfDescriptiveness, twitter_isForgettingHypermedia, twitter_isIgnoringCaching, twitter_isIgnoringMIMEType, twitter_isIgnoringStatusCode, twitter_isMisusingCookies, twitter_AmorphousURI, twitter_ContextlessResource, twitter_CRUDyURI, twitter_NonHierarchicalNodes, twitter_PluralisedNodes), nrow=8,
ncol=11,byrow = TRUE)

dimnames(mydata) = list(c("bitly", "imgur", "vimeo", "disqus", "facebook", "github", "stackExchange", "twitter"),
c("isBreakingSelfDescriptiveness", "isForgettingHypermedia", "isIgnoringCaching", "isIgnoringMIMEType", "isIgnoringStatusCode", "isMisusingCookies", "AmorphousURI", "ContextlessResource", "CRUDyURI", "NonHierarchicalNodes", "PluralisedNodes")

chisq.test(mydata)
